apiVersion: v2
name: kimai2
description: A Helm chart for Kubernetes
type: application
version: 4.1.3
appVersion: "apache-2.18.0-prod"

dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 11.5.7
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
